import os
import json
import subprocess
import re
import getpass
import platform
from fastapi import APIRouter, Request

router = APIRouter()

CURRENT_API_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(CURRENT_API_DIR, "..", ".."))
CONFIG_FILE = os.path.join(PROJECT_ROOT, "data", "deploy_config.json")


@router.get("/config")
async def get_deploy_config():
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except:
            pass
    # 🌟 默认返回双轨结构
    return {
        "blogPath": "",
        "staticRepoUrl": "",
        "staticBranch": "gh-pages",
        "sourceRepoUrl": "",
        "sourceBranch": "master"
    }


@router.post("/config")
async def save_deploy_config(request: Request):
    try:
        data = await request.json()
        os.makedirs(os.path.dirname(CONFIG_FILE), exist_ok=True)
        with open(CONFIG_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return {"success": True, "message": "✅ 双轨部署配置已永久保存！"}
    except Exception as e:
        return {"success": False, "message": f"保存失败: {str(e)}"}


# 🔑 核心大升级：根据 type 动态获取/生成不同的 SSH 密匙，并自动配置路由！
@router.get("/ssh/key")
async def get_my_ssh_key(type: str = "static"):
    """获取或生成本地 SSH 公钥 (支持 A/B 双线隔离)"""
    try:
        ssh_dir = os.path.expanduser("~/.ssh")
        os.makedirs(ssh_dir, exist_ok=True)

        # 判断是为 A线(static) 还是 B线(source) 打钥匙
        if type == "source":
            key_name = "id_ed25519_source"
            user_tag = f"{getpass.getuser()}@{platform.node()}-Source"
        else:
            key_name = "id_ed25519"
            user_tag = f"{getpass.getuser()}@{platform.node()}-Static"

        pub_key_path = os.path.join(ssh_dir, f"{key_name}.pub")
        priv_key_path = os.path.join(ssh_dir, key_name)

        # 兼容老用户：如果是 A 线，优先看看有没有老的 id_rsa
        if type == "static" and not os.path.exists(pub_key_path):
            if os.path.exists(os.path.join(ssh_dir, "id_rsa.pub")):
                pub_key_path = os.path.join(ssh_dir, "id_rsa.pub")

        # 如果连指定的钥匙都没有，当场打一把新的！
        if not os.path.exists(pub_key_path):
            subprocess.run([
                "ssh-keygen", "-t", "ed25519",
                "-C", user_tag,
                "-N", "",
                "-f", priv_key_path
            ], check=True)
            pub_key_path = f"{priv_key_path}.pub"

        # 🌟 极客魔法：如果是 B 线(source)，自动在本地注入 SSH 路由分流规则！
        if type == "source":
            config_path = os.path.join(ssh_dir, "config")
            # 兼容 Windows 和 Mac 路径分隔符
            safe_priv_path = priv_key_path.replace('\\', '/')
            config_entry = f"\n# Auto-generated by Blog CMS for Vercel Source Sync\nHost github-source\n    HostName github.com\n    User git\n    IdentityFile {safe_priv_path}\n"

            config_exists = False
            if os.path.exists(config_path):
                with open(config_path, "r", encoding="utf-8") as f:
                    if "Host github-source" in f.read():
                        config_exists = True

            if not config_exists:
                with open(config_path, "a", encoding="utf-8") as f:
                    f.write(config_entry)

        # 读取公钥内容并返回给前端
        with open(pub_key_path, "r", encoding="utf-8") as f:
            key_content = f.read().strip()
            return {"success": True, "key": key_content}

    except Exception as e:
        return {"success": False, "message": f"获取 SSH 失败: {str(e)}"}


@router.post("/check")
async def check_git_env(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": "本地物理路径不存在，请先检查路径！"}

        git_dir = os.path.join(blog_path, ".git")
        if not os.path.exists(git_dir):
            return {"success": False, "message": "该路径未初始化 Git 仓库，请点击下方【一键初始化】按钮。"}

        return {"success": True, "message": "✅ Git 环境正常！已准备就绪。"}
    except Exception as e:
        return {"success": False, "message": f"Git 检测失败: {str(e)}"}


@router.post("/init")
async def init_deploy_env(request: Request):
    """初始化双轨部署环境"""
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()
        static_repo = payload.get("staticRepoUrl", "").strip()

        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": "目标博客路径不存在！"}

        # 1. 基础 Git 初始化
        subprocess.run(["git", "init"], cwd=blog_path, check=True)

        # 为了兼容老版的静态部署插件，我们把 origin 绑定给 A线 (静态仓库)
        if static_repo:
            subprocess.run(["git", "remote", "remove", "origin"], cwd=blog_path, stderr=subprocess.DEVNULL)
            subprocess.run(["git", "remote", "add", "origin", static_repo], cwd=blog_path, check=True)

        # 2. 修改 package.json 写入 scripts (专供 A 线静态发布)
        pkg_path = os.path.join(blog_path, "package.json")
        if os.path.exists(pkg_path):
            with open(pkg_path, "r", encoding="utf-8") as f:
                pkg_data = json.load(f)
            if "scripts" not in pkg_data:
                pkg_data["scripts"] = {}
            pkg_data["scripts"]["deploy"] = "next build && gh-pages -d out"
            with open(pkg_path, "w", encoding="utf-8") as f:
                json.dump(pkg_data, f, indent=2, ensure_ascii=False)

        # 3. 安装 gh-pages 插件
        process = subprocess.Popen(
            ["npm", "install", "gh-pages", "--save-dev"],
            cwd=blog_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            shell=True,
            text=True,
            encoding='utf-8'
        )
        stdout, stderr = process.communicate()

        return {"success": True, "message": "✨ 太棒了！双轨部署底层依赖与配置初始化完成！"}
    except Exception as e:
        return {"success": False, "message": f"初始化发生异常: {str(e)}"}


# 🚀 A 线接口：打包静态文件并发布到 GitHub Pages
@router.post("/publish")
async def publish_to_github_pages(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        process = subprocess.Popen(
            ["npm", "run", "deploy"],
            cwd=blog_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            shell=True,
            text=True,
            encoding='utf-8'
        )
        stdout, stderr = process.communicate()
        if process.returncode == 0:
            return {"success": True, "message": "🎉 A线: 网页已成功编译并发布到静态仓库！"}
        else:
            return {"success": False, "message": f"发布失败，报错:\n{stderr}"}
    except Exception as e:
        return {"success": False, "message": f"静态发布引擎崩溃: {str(e)}"}


# ☁️ B 线接口：同步源代码到 GitHub，触发 GitHub Actions 自动部署
@router.post("/source")
async def sync_source_to_github(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        # 读取配置
        if not os.path.exists(CONFIG_FILE):
            return {"success": False, "message": "未找到配置文件，请先点击保存！"}

        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            config = json.load(f)

        source_repo = config.get("sourceRepoUrl", "").strip()
        source_branch = config.get("sourceBranch", "master").strip()

        if not source_repo:
            return {"success": False, "message": "源码仓库地址为空，无法同步！"}

        os.chdir(blog_path)

        # 将 SSH 地址转换为 HTTPS 地址（使用 Windows 凭据管理器中的 token）
        if source_repo.startswith("git@github.com:"):
            repo_path = source_repo.replace("git@github.com:", "")
            https_repo = f"https://github.com/{repo_path}"
        else:
            https_repo = source_repo

        # 1. 先拉取远程最新代码，避免后续推送被拒绝
        pull_result = subprocess.run(
            f'git pull "{https_repo}" {source_branch} --rebase --autostash',
            shell=True, capture_output=True, text=True, encoding='utf-8'
        )
        if pull_result.returncode != 0:
            print(f"\n[git pull 警告] 拉取远程代码异常（可能只是没有共同祖先）:")
            print(pull_result.stderr)
            # 不直接返回失败——可能只是第一次推送还没有共同祖先

        # 2. 添加所有代码改动
        subprocess.run(["git", "add", "."], check=True)

        # 3. 提交代码
        commit_result = subprocess.run(
            'git commit -m "Auto sync source code 🚀"',
            shell=True, capture_output=True, text=True, encoding='utf-8'
        )

        if commit_result.returncode != 0:
            return {"success": True, "message": "✅ 本地无新增变更，无需推送。GitHub Actions 会使用上次的构建。"}

        # 4. 推送到 GitHub（GitHub Actions 会自动构建并部署到 Cloudflare Workers）
        push_process = subprocess.run(
            f'git push "{https_repo}" HEAD:{source_branch}',
            shell=True, capture_output=True, text=True, encoding='utf-8'
        )

        if push_process.returncode != 0:
            return {"success": False, "message": f"源码同步失败:\n{push_process.stderr}"}

        return {"success": True, "message": "✅ 代码已推送到 GitHub，GitHub Actions 正在自动构建并部署到 Cloudflare Workers…"}

    except Exception as e:
        return {"success": False, "message": f"部署引擎异常: {str(e)}"}