// Auto-generated by scripts/generate-content-data.js
// DO NOT EDIT MANUALLY — run 'npm run build' to regenerate.

export const momentsData = [
  {
    "slug": "moment-1781961607843",
    "id": "moment-1781961607843",
    "date": "2026-06-20T13:20:07.843Z",
    "images": [
      "https://img.cdn1.vip/i/6a36931a34758_1781961498.webp",
      "https://img.cdn1.vip/i/6a36931ec8259_1781961502.webp"
    ],
    "content": "雷霆国家反诈中心，我在学校的时候说我被电信诈骗了"
  },
  {
    "slug": "moment-1783073738568",
    "id": "moment-1783073738568",
    "date": "2026-07-03T10:15:38.568Z",
    "content": "测试"
  }
] as const;
export const chattersData = [
  {
    "slug": "chatter_1781965195",
    "title": "测试",
    "date": "2026-06-20 22:19:55",
    "tags": [],
    "mood": "",
    "cover": "",
    "description": "",
    "content": "测试测试"
  }
] as const;
export const postsData = [] as const;
